# Generated by Django 5.2.5 on 2025-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('SunTrack Services', 'SUNTRACK SERVICES'), ('Planos SunTrack', 'PLANOS SUNTRACK'), ('GoodWe Services', 'GOODWE SERVICES')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='imagem/%Y/%m/%d')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
